version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - mkdir $ANDROID_HOME/licenses
      - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew --debug --stacktrace build
  post_build:
    commands:
      - echo Build completed on `date`
